[it]
  languageName = "Italian"
  languageCode = "it-IT"
  weight = 10
  [it.params]
    languageISO = "IT"

[en]
  disabled = true
  languageName = "English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"