# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Team Manalisk: professionisti esperti di intelligenza artificiale (AI), con esperienza nell'integrazione delle nuove tecnologie in contesti aziendali"
shortDescription = "Intelligenza Artificiale per il tuo business"
images = ['images/manalisk.png']
mainMenuLogo = "images/manalisk.png"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
#alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = false
  listTagFilter = false