[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "Chi Siamo"
url = "about"
weight = 20
title = "Scopri di più sulla nostra missione"


[[main]]
name = "Servizi"
url = "services"
weight = 30
title = "Scopri i nostri servizi"

[[main]]
name = "Formazione"
url = "formazione-intelligenza-artificiale-e-cybersecurity"
weight = 31
title = "Scopri i nostri corsi di formazione AI e Cybersecurity"
#[[main]]
#identifier = "blog"
#name = "Blog"
#url = "post"
#weight = 40
#title = "Leggi i nostri articoli"
