[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "About"
url = "about"
weight = 20
title = "About us"


[[main]]
name = "Services"
url = "/services/"
weight = 30
title = "Discover our services"

#[[main]]
#identifier = "blog"
#name = "Blog"
#url = "post"
#weight = 40
#title = "Read our blog"
